const p=window.PROJECT,$=s=>document.querySelector(s),pad=n=>String(n).padStart(2,'0');
p.asset=n=>`assets/hd/p${pad(n)}.webp`;
const pic=(n,alt,cls='')=>`<img class="${cls}" src="${p.asset(n)}" alt="${alt}" loading="lazy">`;
const spaceSlides=p.spaces.map((s,i)=>`<article class="room" id="room-${s.id}"><div class="room-copy"><small>${pad(i+1)} / ${pad(p.spaces.length)}</small><p>${s.en}</p><h2>${s.name}</h2><span>${s.summary}</span></div><div class="room-images">${s.pages.slice(0,3).map((n,j)=>`<button class="${j===0?'main':''}" data-image="${p.asset(n)}" aria-label="放大${s.name}图片">${pic(n,s.name)}</button>`).join('')}</div></article>`).join('');
document.body.innerHTML=`<header><a href="#top" class="mark">合止间<span>H SPACE</span></a><button class="menu" aria-expanded="false">INDEX</button><nav><a href="#story">项目</a><a href="#idea">理念</a><a href="#plan">平面</a><a href="#rooms">空间</a><a href="#decision">确认</a></nav><i class="meter"></i></header>
<main id="top">
<section class="hero"><div class="hero-media">${pic(18,'天樾玺空间氛围')}</div><div class="veil"></div><div class="hero-title"><p>${p.version} · ${p.date}</p><h1>天樾玺<br><em>16—1501</em></h1><span>PRIVATE RESIDENCE · CHANGZHOU</span></div><div class="hero-side">SPACE<br>ART<br>ARCHITECTURE</div><a class="scroll" href="#story">SCROLL TO EXPLORE <b>↓</b></a></section>
<section id="story" class="statement"><div class="chapter"><b>01</b><span>THE BEGINNING</span></div><div class="statement-copy reveal"><p>设计不是填满空间，<br>而是为生活留下发生的余地。</p><small>${p.quote}</small></div><div class="project-facts">${p.facts.map(x=>`<div><small>${x.label}</small><b>${x.value}</b></div>`).join('')}</div></section>
<section class="site-cinema"><div class="site-cinema-image">${pic(6,'基地环境')}</div><div class="site-caption"><span>SITE CONDITIONS</span><h2>透 · 光 · 风<br>尺度与视线</h2><p>场地带来的自然条件，不是限制，而是空间秩序的起点。</p></div></section>
<section id="idea" class="idea"><div class="chapter light"><b>02</b><span>DESIGN CONCEPT</span></div><div class="idea-head reveal"><h2>实<span>与</span>虚</h2><p>THE SOLID<br>+ THE VOID</p></div><div class="idea-grid"><figure class="tall">${pic(9,'实体躯壳')}<figcaption><b>实体 · 躯壳</b><span>STRUCTURE / STORAGE / PLANE</span></figcaption></figure><div class="idea-note"><p>${p.concept.intro}</p><i></i><span>风与光不是装饰，<br>它们是时间进入住宅的方式。</span></div><figure>${pic(10,'虚体精神')}<figcaption><b>虚体 · 精神</b><span>SERENITY / REFLECTION / LIFE</span></figcaption></figure></div></section>
<section class="light-pair"><figure>${pic(11,'风')}<figcaption><b>WIND</b><span>流动、雨水与时间痕迹</span></figcaption></figure><figure>${pic(12,'光')}<figcaption><b>LIGHT</b><span>光随时刻移动</span></figcaption></figure></section>
<section id="plan" class="plan"><div class="chapter"><b>03</b><span>SPATIAL STRATEGY</span></div><div class="plan-head reveal"><h2>空间不是房间的集合，<br>而是一条连续的生活路径。</h2><p>PLAN · 104 m²</p></div><div class="plan-stage"><div class="plan-tabs">${p.plans.map((x,i)=>`<button data-plan="${i}" class="${i?'':'active'}"><span>0${i+1}</span>${x.name}</button>`).join('')}</div><figure>${pic(15,'方案平面','plan-image')}<figcaption>方案平面 A</figcaption></figure></div></section>
<section id="rooms" class="rooms"><div class="rooms-opening"><div class="chapter light"><b>04</b><span>SPACE JOURNEY</span></div><div><p>ROOM BY ROOM</p><h2>走进空间</h2></div><span>向下浏览每一个生活场景</span></div>${spaceSlides}</section>
<section id="decision" class="decision"><div class="chapter"><b>05</b><span>NEXT STEPS</span></div><div class="decision-grid"><div class="reveal"><p>NEXT STEPS</p><h2>从共识开始，<br>走向落地。</h2><span>请确认以下事项，我们将进入下一阶段。</span></div><ol>${p.next.map((x,i)=>`<li><span>${pad(i+1)}</span><p>${x}</p><label><input type="checkbox">确认</label></li>`).join('')}</ol></div><button class="approve">完成本轮确认 <i>→</i></button><small class="status">确认状态仅保存在本机。</small></section>
<footer><span>${p.studio}</span><strong>THANK<br>YOU.</strong><p>${p.title} ${p.unit}<br>${p.date}</p></footer></main>
<dialog><button class="close">×</button><img alt="方案大图"></dialog>`;
document.addEventListener('click',e=>{const t=e.target.closest('[data-plan]');if(t){const x=p.plans[+t.dataset.plan];$('.plan-image').src=p.asset(x.page);$('.plan-stage figcaption').textContent=x.name;document.querySelectorAll('[data-plan]').forEach(b=>b.classList.toggle('active',b===t))}const z=e.target.closest('[data-image]');if(z){$('dialog img').src=z.dataset.image;$('dialog').showModal()}if(e.target.closest('.close')||e.target=== $('dialog'))$('dialog').close()});
const m=$('.menu');m.onclick=()=>{const open=$('header nav').classList.toggle('open');m.setAttribute('aria-expanded',open)};$('header nav').onclick=()=>{$('header nav').classList.remove('open');m.setAttribute('aria-expanded','false')};
addEventListener('scroll',()=>$('.meter').style.width=`${scrollY/(document.documentElement.scrollHeight-innerHeight)*100}%`,{passive:true});
const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.1});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));
const key='tianyuexi-v2-checks',inputs=[...document.querySelectorAll('.decision input')],saved=JSON.parse(localStorage.getItem(key)||'[]');inputs.forEach((x,i)=>{x.checked=!!saved[i];x.onchange=()=>localStorage.setItem(key,JSON.stringify(inputs.map(y=>y.checked)))});$('.approve').onclick=()=>$('.status').textContent=inputs.every(x=>x.checked)?'✓ 本轮事项已全部确认':'请先逐项确认以上内容';
